name: Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Test
        run: dpkg-deb --build $(uv run debby --file ./README.md /usr/bin/debby --pyproject -o ./dist)